app/models/__init__.py
from .user import UserLogin, UserModel
from .teacher import TeacherForm

app/models/teacher.py
from flask_wtf import FlaskForm
from wtforms import StringField, HiddenField
from wtforms.validators import DataRequired


class TeacherForm(FlaskForm):
    name = StringField("Nombre", validators=[DataRequired()])
    subject = StringField("Materia", validators=[DataRequired()])

app/models/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email
from flask_login import UserMixin


class UserLogin(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    passwd = PasswordField('Password', validators=[DataRequired()])


class UserModel(UserMixin):
    def __init__(self, user) -> None:
        self.id = user['username']
        self.email = user['email']
        self.rol = user['rol']

app/__init__.py
from flask import Flask
from .config import Config
from .utils.fl_login import login_manager
from flask_cors import CORS


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    login_manager.init_app(app)
    CORS(app)

    from .routes import index_bp
    app.register_blueprint(index_bp)

    from .routes import auth_bp
    app.register_blueprint(auth_bp)

    from .routes import evaluation_bp
    app.register_blueprint(evaluation_bp)

    from .routes import teacher_bp
    app.register_blueprint(teacher_bp)

    return app

app/routes/__init__.py
from .auth import auth_bp
from .evaluation import evaluation_bp

from .teacher import teacher_bp

from flask import Blueprint, render_template
from flask_login import login_required

index_bp = Blueprint('IndexRoute', __name__)


@index_bp.get('/')
@login_required
def index():
    return render_template('index.jinja')

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, make_response, session
from flask_login import login_user, logout_user, current_user
from app.models import UserLogin, UserModel
from app.services.auth import post_login_api

auth_bp = Blueprint('AuthRoute', __name__)


@auth_bp.get('/login')
def get_login():
    if current_user.is_authenticated:
        return redirect(url_for('IndexRoute.index'))

    user_form = UserLogin()
    context = {'form': user_form, 'title': 'Login'}
    return render_template('auth.jinja', **context)


@auth_bp.post('/login')
def post_login():
    user_form = UserLogin()
    if not user_form.validate_on_submit():
        print(user_form.errors)
        flash('Error en el formulario', 'error')
        return redirect(url_for('AuthRoute.get_login'))

    response, error = post_login_api(user_form.data)

    if error is not None:
        flash(error, 'error')
        print(response.json())
        return redirect(url_for('AuthRoute.get_login'))

    data = response.json()

    res = data["response"]
    access_token = res["access_token"]
    user = res["user"]

    session["user"] = user

    user = UserModel(user)

    login_user(user)

    response = make_response(redirect(url_for('IndexRoute.index')))

    response.set_cookie('access_token', access_token)

    return response


@auth_bp.get('/logout')
def get_logout():
    logout_user()
    session.clear()
    # limpiar cookies
    response = make_response(redirect(url_for('AuthRoute.get_login')))
    response.set_cookie('access_token', '')
    return response


@auth_bp.get('/signup')
def get_signup():
    if current_user.is_authenticated:
        return redirect(url_for('IndexRoute.index'))

    user_form = UserLogin()
    context = {'form': user_form, 'title': 'Signup'}

    return render_template('auth.jinja', **context)


@auth_bp.post('/signup')
def post_signup():
    pass

app/routes/evaluation.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from app.services.teacher import get_all_teachers
from app.services.evaluation import delete_evaluation
from app.config import Config

evaluation_bp = Blueprint('EvaluationRoute', __name__,
                          url_prefix='/evaluation')


@evaluation_bp.get('/')
@login_required
def get_evaluation():
    return render_template('evaluation.jinja')


@evaluation_bp.get('/add')
@login_required
def get_add_evaluation():
    access_token = request.cookies.get('access_token')

    res, error = get_all_teachers(access_token)

    if error is not None:
        flash(error, 'danger')

        if error == 'Token has expired':
            return redirect(url_for('AuthRoute.get_logout'))

        return redirect(url_for('EvaluationRoute.get_evaluation'))

    teachers = res.json()['result']

    context = {
        'teachers': teachers,
        'URL_API': Config.URL_API
    }

    return render_template('evaluation_add_edit.jinja', **context)


@evaluation_bp.get('/edit/<id>')
@login_required
def get_edit_evaluation(id):
    access_token = request.cookies.get('access_token')

    res, error = get_all_teachers(access_token)

    if error is not None:
        flash(error, 'danger')

        if error == 'Token has expired':
            return redirect(url_for('AuthRoute.get_logout'))

        return redirect(url_for('EvaluationRoute.get_evaluation'))

    teachers = res.json()['result']
    context = {
        'id': id,
        'teachers': teachers,
        'URL_API': Config.URL_API
    }
    return render_template('evaluation_add_edit.jinja', **context)


@evaluation_bp.get('/delete/<id>')
@login_required
def get_detail_evaluation(id):
    access_token = request.cookies.get('access_token')
    res, error = delete_evaluation(access_token, id)

    if error is not None:
        flash(error, 'danger')

        if error == 'Token has expired':
            return redirect(url_for('AuthRoute.get_logout'))

        return redirect(url_for('EvaluationRoute.get_evaluation'))

    if res.json()['status'] != 'ok':
        flash(res.json()['msg'], 'danger')
        return redirect(url_for('EvaluationRoute.get_evaluation'))

    flash("Evaluación eliminado correctamente", 'success')
    return redirect(url_for('EvaluationRoute.get_evaluation'))

app/routes/teacher.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from app.models import TeacherForm

teacher_bp = Blueprint("TeacherRoute", __name__, url_prefix="/teacher")


@teacher_bp.get("/")
@login_required
def get_teacher():
    return render_template("teacher.jinja")


@teacher_bp.get("/add")
@login_required
def get_add_teacher():
    context = {
        "action": "agregar",
        "form": TeacherForm()
    }
    return render_template("teacher_form.jinja", **context)


@teacher_bp.post("/add")
@login_required
def post_add_teacher():

    teacher_form = TeacherForm()

    if not teacher_form.validate_on_submit():
        flash("Datos no validos")
        return redirect(url_for("TeacherRoute.get_add_teacher"))

    print(teacher_form.data)

    return redirect(url_for("TeacherRoute.get_add_teacher"))

app/services/auth.py
import requests
from app.config import Config
URL_BASE = Config.URL_API + '/auth'


def post_login_api(user_form):
    try:
        url = f'{URL_BASE}/login'
        response = requests.post(url, json=user_form)

        if response.status_code != 200:
            return response, response.json()['msg']

        if not response.json():
            return response, "Error en el servidor"

        if response.json()['status'] == 'error':
            return response, response.json()['msg']

        return response, None
    except Exception as e:
        print(e)
        return None, "Error en el servidor"

app/templates/auth.jinja
{% extends "base.jinja" %}
{% from "macros/_navbar.jinja" import navbar %}


{% block header %}
{{ super() }}
{{ navbar(current_user,"login") }}
{% endblock header %}

{% block content %}
<h1>{{title}}</h1>
<form action="" method="post">
    {{form.csrf_token}}
    <fieldset>
        <legend>{{form.username.label}}</legend>
        {{form.username}}
    </fieldset>
    <fieldset>
        <legend>{{form.passwd.label}}</legend>
        {{form.passwd}}
    </fieldset>
    <button type="submit">Enviar</button>
</form>
{% endblock %}

app/templates/base.jinja
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock title %}</title>
    {% block styles %}
    {% endblock styles %}
</head>

<body>
    <header>
        {% block header %}
        {% endblock header %}
    </header>
    {% for category,message in get_flashed_messages(with_categories=true) %}
    <div class="flash flash-{{category}}">{{ message }}</div>
    {% endfor %}
    {% block content %}
    {% endblock content %}
    {% block scripts %}
    <script type="module" src="{{url_for('static',filename='js/token.js')}}"></script>
    {% endblock scripts %}
</body>

</html>

app/templates/evaluation.jinja
{% extends "base.jinja" %}
{% from "macros/_navbar.jinja" import navbar %}

{% block title %}Evaluaciones{% endblock %}

{% block header %}
{{ super() }}
{{ navbar(current_user,"evaluation") }}
{% endblock header %}
{% block content %}
<h1>Evaluaciones</h1>
<a href="{{url_for('EvaluationRoute.get_add_evaluation')}}">Agregar</a>

<section id="containerEvaluation">

</section>
{% endblock %}

{% block scripts %}
{{ super() }}
<script type="module" src="{{url_for('static', filename='js/services/evaluation.js')}}"></script>
<script type="module" src="{{url_for('static', filename='js/evaluation.js')}}"></script>
{% endblock scripts %}

app/templates/evaluation_add.jinja
{% extends "base.jinja" %}
{% from "_navbar.jinja" import navbar %}

{% block title %}
Evaluación docente
{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{{url_for('static',filename='/css/Global.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename='/css/evaluation.css')}}" />
{% endblock styles %}

{% block header %}
{{ super() }}
{{ navbar(current_user,"") }}
{% endblock header %}

{% block content %}
<main>
  <article id="questionArticle">

    <section id="dataEvaluation">
      <input type="hidden" id="id" name="id" value="">
      <input type="text" id="title" value="Titulo" placeholder="Titulo">
      <label for="id_teacher">
        <span class="label_teacher">Seleccione un docente</span>
        <select name="id_teacher" id="id_teacher">
          {% if teachers %}
          {% for teacher in teachers %}
          <option value="{{teacher.id}}">{{teacher.name}}</option>
          {% endfor %}
          {% endif %}
        </select>
      </label>
    </section>
    <section id="ListQuestion">
      <question-editor></question-editor>
    </section>
  </article>
  <article id="container-btn">
    <button class="btn" id="btnSave" type="button">Guardar</button>
    <button class="btn" id="btnAddQuestion" type="button">Agregar</button>
  </article>
</main>
{% endblock content %}

{% block scripts %}
{{ super() }}
<script type="module" src="{{url_for('static',filename='/js/services/evaluation.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/context/contextListQuestion.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/InputItem.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/BaseListInput.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/ListRadioInput.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/ListCheckBoxInput.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/TextAreaInput.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/QuestionEditor.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/generateEvaluation.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/customElements.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/elements.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/main.js')}}"></script>
{% endblock scripts %}

app/templates/evaluation_add_edit.jinja
{% extends "base.jinja" %}
{% from "macros/_navbar.jinja" import navbar %}

{% block title %}
Evaluación docente
{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{{url_for('static',filename='/css/Global.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename='/css/evaluation.css')}}" />
{% endblock styles %}

{% block header %}
{{ super() }}
{{ navbar(current_user,"") }}
{% endblock header %}

{% block content %}
<main>
  <article id="questionArticle">

    <section id="dataEvaluation">
      <input type="hidden" id="id" name="id" value="{{id}}">
      <input type="text" id="title" value="Titulo" placeholder="Titulo">
      <label for="id_teacher">
        <span class="label_teacher">Seleccione un docente</span>
        <select name="id_teacher" id="id_teacher">
          {% if teachers %}
          {% for teacher in teachers %}
          <option value="{{teacher.id}}">{{teacher.name}}</option>
          {% endfor %}
          {% endif %}
        </select>
      </label>
    </section>
    <section id="ListQuestion">
      <question-editor></question-editor>
    </section>
  </article>
  <article id="container-btn">
    <button class="btn" id="btnSave" type="button">Guardar</button>
    <button class="btn" id="btnAddQuestion" type="button">Agregar</button>
  </article>
</main>
{% endblock content %}

{% block scripts %}
{{ super() }}
<script type="module" src="{{url_for('static',filename='/js/services/evaluation.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/context/contextListQuestion.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/InputItem.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/BaseListInput.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/ListRadioInput.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/ListCheckBoxInput.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/TextAreaInput.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/components/QuestionEditor.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/generateEvaluation.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/customElements.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/elements.js')}}"></script>
<script type="module" src="{{url_for('static',filename='/js/main.js')}}"></script>
{% endblock scripts %}

app/templates/index.jinja
{% extends "base.jinja" %}
{% from"macros/_navbar.jinja" import navbar %}

{% block header %}
{{navbar(current_user,"home")}}
{% endblock header %}

{% block content %}

<h1>Dashboard</h1>

<a href="{{url_for('EvaluationRoute.get_evaluation')}}">Lista de Evaluaciones</a>
<hr>
<a href="{{url_for('TeacherRoute.get_teacher')}}">Lista de Maestros</a>

{% endblock content %}

app/templates/macros/_navbar.jinja
{% macro navbar(current_user,page) %}
<nav>
    <ul>
        {% if current_user.is_authenticated %}
        <li class="{% if page == 'home' %}active{% endif %}">
            <a href="{{url_for('IndexRoute.index')}}">Welcome, {{ current_user.id | capitalize }}</a>
        </li>
        <li class="{% if page == 'teacher' %}active{% endif %}"><a
                href="{{url_for('TeacherRoute.get_teacher')}}">Maestros</a></li>

        <li class="{% if page == 'evaluation' %}active{% endif %}"><a
                href="{{url_for('EvaluationRoute.get_evaluation')}}">Evaluation</a></li>

        <li class="{% if page == 'home' %}active{% endif %}"><a href="{{url_for('AuthRoute.get_logout')}}">Logout</a>
        </li>
        {% else %}
        <li class="{% if page == 'signup' %}active{% endif %}"><a href="{{url_for('AuthRoute.get_signup')}}">Signup</a>
        </li>
        <li class="{% if page == 'login' %}active{% endif %}"><a href="{{url_for('AuthRoute.get_login')}}">Login</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}

app/templates/teacher.jinja
{% extends "base.jinja" %}
{% from "macros/_navbar.jinja" import navbar %}

{% block title %}
Lista de Maestros
{% endblock title %}

{% block header %}
{{ super() }}
{{ navbar(current_user,"teacher") }}
{% endblock header %}

{% block content %}
<h1>Maestros</h1>
<a href="{{url_for('TeacherRoute.get_add_teacher')}}">Agregar</a>
<section id="containerTeacher"> </section>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ super() }}
<script type="module" src="{{url_for('static', filename='js/services/teacher.js')}}"></script>
<script type="module" src="{{url_for('static', filename='js/teacher.js')}}"></script>
{% endblock scripts %}

app/templates/teacher_form.jinja
{% extends "base.jinja" %}
{% from "macros/_navbar.jinja" import navbar %}

{% block title %}{{action | capitalize}} maestros{% endblock title %}


{% block header %}
{{ super() }}
{{ navbar(current_user,"teacher") }}
{% endblock header %}

{% block content %}
<h1>{{ action | capitalize }}</h1>
<section>
    {% if form.name.errors %}
    <ul class="errors">
        {% for error in form.name.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</section>
{% if teacher %}
<form action="" method="post">
    {{form.csrf_token}}
    <fieldset>
        <legend>{{form.name.label}}</legend>
        {{form.name(value=teacher.name)}}
    </fieldset>
    <fieldset>
        <legend>{{form.subject.label}}</legend>
        {{form.subject(value=teacher.subject)}}
    </fieldset>

    <button type="submit">Enviar</button>
</form>
{% else %}
<form action="" method="post">
    {{form.csrf_token}}
    <fieldset>
        <legend>{{form.name.label}}</legend>
        {{form.name}}
    </fieldset>
    <fieldset>
        <legend>{{form.subject.label}}</legend>
        {{form.subject}}
    </fieldset>

    <button type="submit">Enviar</button>
</form>
{% endif %}

{% endblock content %}